#profiles
ACTIVE_PROFILE: dev

#database
MYSQL_HOST: localhost
MYSQL_PORT: 3306
MYSQL_DATABASE: dev
MYSQL_USERNAME: root
MYSQL_PASSWORD: root

#server
CONTAINER_PORT: 8080

SECRET_KEY : "a3f5e0b9c2b57d8f1e1c3c4a2c6c7e1f8d3b6e2c5a7d8f9e0f1a2b3c4d5e6f7"